# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Let's Make a (Web) Podcast
email: josh@joshrucker.com
description: A podcast about the web, new technology, and being a professional in the 21st century.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.letsmakeapodcast.org" # the base hostname & protocol for your site
twitter_username: ifiamblue
github_username:  ifiamblue

# Build settings
markdown: kramdown
